title: Awesome-courses
description: ":books: List of awesome university courses for learning Computer Science!"
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
